// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:c4ce2cd2-e012-4a05-8044-d09bed1058c0",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_tvTwM741D",
    "aws_user_pools_web_client_id": "58k7sll635hvaicdvp03nulrue"
};


export default awsmobile;
